'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'public/game.html'), 'utf8');
const game = fs.readFileSync(path.join(root, 'public/game.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'public/styles.css'), 'utf8');
const network = fs.readFileSync(path.join(root, 'public/network-client.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const advanced = fs.readFileSync(path.join(root, 'public/ai-model-advanced.js'), 'utf8');

assert(html.includes('value="advanced-v1">高级</option>'), '高级模型应出现在人机菜单');
assert(html.includes('ai-model-advanced.js'), '网页应加载高级模型权重');
assert(advanced.includes('DoubleFlightAIModelAdvanced'), '高级模型应使用独立全局名称');
assert(game.includes("intervalMs: 500"), '游戏端普通轮询应为500ms');
assert(network.includes('options.intervalMs || 500'), '网络客户端默认轮询应为500ms');
assert(server.includes('pollingIntervalMs: 500'), '服务端信息应报告500ms轮询');
assert(html.includes('leftColumnResizer') && html.includes('rightColumnResizer'), '左右栏应有拖动分隔条');
assert(game.includes('initWorkspaceResizers') && css.includes('.column-resizer'), '左右栏拖动实现应完整');
assert(game.includes('initChatPanelResizers') && css.includes('.lan-chat-resize-handle'), '游戏聊天卡片应可调高度');
assert(server.includes('chatResizeHandle') && server.includes('doubleFlightAdminChatHeight'), '服务端聊天卡片应可调高度');
assert(css.includes('@keyframes lan-chat-attention') && css.includes('--lan-unread-color: #e7b928'), '聊天提示应使用未读黄色闪烁');
assert(html.includes('lanSpiritLayer') && game.includes("launchLanSpirit('chat')") && game.includes("launchLanSpirit('turn')"), '两类联机灵动动画应存在');
assert(css.includes('z-index: 1250') && css.includes('pointer-events: none'), '灵动动画层应位于弹窗下且不阻挡操作');
console.log('v0.39 UI/model static tests passed');
